version: "3.7"
services:
  bot:
    image: kyb3rr/modmail
    restart: always
    env_file:
      - .env
    environment:
      - CONNECTION_URI=mongodb://mongo
    depends_on:
      - mongo
  viewer:
    image: ghcr.io/khakers/modmail-viewer:latest
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "80:7070"
    environment:
      - "MODMAIL_VIEWER_MONGODB_URI=mongodb://mongo:27017"
      - "MODMAIL_VIEWER_URL=http://127.0.0.1:80"
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: